dist: trusty
sudo: required
services:
    - docker

before_install:
    - docker pull java:8

before_script: chmod +x gradlew

script:
    - docker run -v $(pwd):/build java:8 /bin/sh -c 'cd /build; ./gradlew --no-daemon --stacktrace clean build'
