INSERT INTO TEAM (TEAM_ID, NAME) VALUES (1, 'FARADAY');
INSERT INTO TEAM (TEAM_ID, NAME) VALUES (2, 'GAUSS');
INSERT INTO TEAM (TEAM_ID, NAME) VALUES (3, 'PLANCK');

INSERT INTO USER (USER_ID, TEAM_ID, NAME) VALUES (1, 1, 'wmilczarek');
INSERT INTO USER (USER_ID, TEAM_ID, NAME) VALUES (2, 2, 'dkierecki');
INSERT INTO USER (USER_ID, TEAM_ID, NAME) VALUES (3, 3, 'wiget');
INSERT INTO USER (USER_ID, TEAM_ID, NAME) VALUES (4, 2, 'mateuszmarek');
INSERT INTO USER (USER_ID, TEAM_ID, NAME) VALUES (5, 1, 'ThePnx');
INSERT INTO USER (USER_ID, TEAM_ID, NAME) VALUES (6, 2, 'Vortim');

INSERT INTO PULL_REQUEST (PULL_REQUEST_ID, TITLE, STATUS, URL, USER_ID,TEAM_ID)
VALUES ('111', 'TITLE', 'TAKEN', 'URL', 1, 2);
INSERT INTO PULL_REQUEST (PULL_REQUEST_ID, TITLE, STATUS, URL, USER_ID,TEAM_ID)
VALUES ('222', 'TITLE', 'CLOSED', 'URL', 1, 1);
INSERT INTO PULL_REQUEST (PULL_REQUEST_ID, TITLE, STATUS, URL, USER_ID,TEAM_ID)
VALUES ('333', 'TITLE', 'ASSIGNED', 'URL', 1, 2);
